### PR TITLE
Import `bool` from @ember/object/computed

### PR DESCRIPTION
**Pull request by aoumiri**
This resolves https://github.com/stefanpenner/ember-moment/issues/340

There were 6 tests failing before making the change, not sure if that's something we should worry about?

### CODE REVIEW

**Comment by aoumiri** [comment]
Hello @stefanpenner, any idea on how to make the pipeline pass?
It looks like the node version it's using is different from the one expected.

**Comment by jacobq** [comment]
> Hello @stefanpenner, any idea on how to make the pipeline pass?
> It looks like the node version it's using is different from the one expected.

```
error resolve-package-path@3.1.0: The engine "node" is incompatible with this module. Expected version "10.* || >= 12". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "yarn install --no-lockfile --non-interactive" failed and exited with 1 during .
```

`resolve-package-path` v4.0.0 was just released (5/10/2021) also, which drops support for node 10. Seems like an appropriate time to drop node 8 and 10 here (both [EOL](https://nodejs.org/en/about/releases/)). I'll take a shot at fixing CI in a separate PR and hopefully that'll help land this one (which is keeping me from being able to upgrade my app to 3.27).

**Comment by jacobq** [comment]
@aoumiri Try adding a yarn resolution to hold the offending package back like I did here:
https://github.com/jacobq/ember-moment/commit/0b5456f3cac5dbc718ea69665da01935dd94b05c
Alternatively, you can wait for the maintainers to drop Node 8 (and maybe also 10) support (requested in PR #346)

**Comment by NullVoxPopuli** [comment]
This is now resolved (as computeds are not used at all in Octane+ ember-moment).

This'll be released in v9 shortly

**Pull request closed without merging**
