### PR TITLE
Update dependency `@embroider/addon-shim` to `^1.8.9`

### PR DESCRIPTION
**Pull request by mkszepp**
fix https://github.com/adopted-ember-addons/ember-moment/issues/377

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I sent this via DM, but for others, here is the plan:

I would de this series of PRs:
- drop support for node < 18 (This is a breaking change, we won't release right away)
- add `@ember/string` to the test app
- _then_ we land your embroider update PR
- then we do a v2 addon

**Review by NullVoxPopuli — APPROVED** [review]
Why use old range || new range?

**Comment by mkszepp** [comment]
> Why use old range || new range?

not sure, if there is something braking between v0.50 and 1.x... but we can also remove v0.50 if you want

**Comment by NullVoxPopuli** [comment]
I don't think anything would break, unless folks are pinning the older versions, which it's their own fault at that point

**Pull request merged**
